/**
 * 生成测试夹具：一张自带 chara / ccv3 区块的极小角色卡。
 *
 * 公开仓库里不放别人做的社区角色卡，所以夹具在测试运行时现场生成。
 * 生成逻辑独立于被测代码（自己算 zlib stored block 与 CRC32），
 * 这样「读回已有角色卡」这条路径仍然是对着一份外部数据验证的，而不是自证。
 */

import { deflateSync } from 'node:zlib';

const CRC_TABLE = (() => {
    const table = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
        table[n] = c >>> 0;
    }
    return table;
})();

function crc32(bytes) {
    let crc = 0xffffffff;
    for (let i = 0; i < bytes.length; i++) crc = CRC_TABLE[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
    return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
    const out = new Uint8Array(12 + data.length);
    const view = new DataView(out.buffer);
    view.setUint32(0, data.length);
    for (let i = 0; i < 4; i++) out[4 + i] = type.charCodeAt(i);
    out.set(data, 8);
    view.setUint32(8 + data.length, crc32(out.subarray(4, 8 + data.length)));
    return out;
}

function concat(parts) {
    const total = parts.reduce((sum, part) => sum + part.length, 0);
    const merged = new Uint8Array(total);
    let offset = 0;
    for (const part of parts) {
        merged.set(part, offset);
        offset += part.length;
    }
    return merged;
}

/** 生成一张 2×2 的灰度 PNG（像素为真，zlib 流合法） */
function makePixels(size = 2) {
    // 每行 1 字节滤波器 + size 字节像素
    const raw = new Uint8Array((size + 1) * size);
    for (let y = 0; y < size; y++) {
        raw[y * (size + 1)] = 0; // filter: none
        for (let x = 0; x < size; x++) {
            raw[y * (size + 1) + 1 + x] = (x * 37 + y * 61) & 0xff;
        }
    }
    return deflateSync(raw, { level: 9 });
}

function textChunk(keyword, text) {
    const keywordBytes = new TextEncoder().encode(keyword);
    const textBytes = new TextEncoder().encode(text);
    const data = new Uint8Array(keywordBytes.length + 1 + textBytes.length);
    data.set(keywordBytes, 0);
    data[keywordBytes.length] = 0;
    data.set(textBytes, keywordBytes.length + 1);
    return chunk('tEXt', data);
}

/**
 * @param {{name?: string, description?: string, first_mes?: string}} overrides
 * @returns {Uint8Array} 一张内嵌 V2 + V3 卡数据的 PNG
 */
export function makeSampleCard(overrides = {}) {
    const data = {
        name: 'Fixture',
        description: '测试夹具角色，由 tests/fixture.mjs 现场生成，不含任何第三方内容。',
        personality: '严谨、可复现。',
        scenario: '单元测试环境。',
        first_mes: '"这是一张用于验证读卡能力的合成角色卡。"',
        mes_example: '<START>\n{{char}}: 你好。\n{{user}}: 你好。',
        creator_notes: 'generated by tests/fixture.mjs',
        alternate_greetings: [],
        tags: ['fixture'],
        creator: 'novel-to-card tests',
        character_version: '1.0',
        extensions: {},
        ...overrides,
    };

    const v2 = { spec: 'chara_card_v2', spec_version: '2.0', data, ...data };
    const v3 = { spec: 'chara_card_v3', spec_version: '3.0', data: { ...data, creation_date: 0, assets: [] }, ...data };

    const toBase64 = (text) => Buffer.from(text, 'utf8').toString('base64');

    const ihdr = new Uint8Array(13);
    const ihdrView = new DataView(ihdr.buffer);
    ihdrView.setUint32(0, 2); // width
    ihdrView.setUint32(4, 2); // height
    ihdr[8] = 8;  // bit depth
    ihdr[9] = 0;  // color type: grayscale
    ihdr[10] = 0; // compression
    ihdr[11] = 0; // filter
    ihdr[12] = 0; // interlace

    return concat([
        new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
        chunk('IHDR', ihdr),
        textChunk('chara', toBase64(JSON.stringify(v2))),
        textChunk('ccv3', toBase64(JSON.stringify(v3))),
        chunk('IDAT', makePixels(2)),
        chunk('IEND', new Uint8Array(0)),
    ]);
}

/** 生成一张没有任何卡数据的普通 PNG */
export function makePlainCard() {
    const ihdr = new Uint8Array(13);
    const view = new DataView(ihdr.buffer);
    view.setUint32(0, 2);
    view.setUint32(4, 2);
    ihdr[8] = 8;
    return concat([
        new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
        chunk('IHDR', ihdr),
        chunk('IDAT', makePixels(2)),
        chunk('IEND', new Uint8Array(0)),
    ]);
}
